//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renamer.UI.Resources.Strings
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan is null)
                {
                    resourceMan = new global::System.Resources.ResourceManager("Renamer.UI.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string MainPageHeading => ResourceManager.GetString("MainPageHeading", resourceCulture)!;
        internal static string MainPageDescription => ResourceManager.GetString("MainPageDescription", resourceCulture)!;

        internal static string WorkflowRailHeader => ResourceManager.GetString("WorkflowRailHeader", resourceCulture)!;
        internal static string WorkflowRailDescription => ResourceManager.GetString("WorkflowRailDescription", resourceCulture)!;

        internal static string StepGenerateTitle => ResourceManager.GetString("StepGenerateTitle", resourceCulture)!;
        internal static string StepGenerateDescription => ResourceManager.GetString("StepGenerateDescription", resourceCulture)!;
        internal static string StepPreviewTitle => ResourceManager.GetString("StepPreviewTitle", resourceCulture)!;
        internal static string StepPreviewDescription => ResourceManager.GetString("StepPreviewDescription", resourceCulture)!;
        internal static string StepApplyTitle => ResourceManager.GetString("StepApplyTitle", resourceCulture)!;
        internal static string StepApplyDescription => ResourceManager.GetString("StepApplyDescription", resourceCulture)!;
        internal static string StepStatusDone => ResourceManager.GetString("StepStatusDone", resourceCulture)!;
        internal static string StepStatusError => ResourceManager.GetString("StepStatusError", resourceCulture)!;
        internal static string StepStatusNeedsInfo => ResourceManager.GetString("StepStatusNeedsInfo", resourceCulture)!;

        internal static string GenerateHeading => ResourceManager.GetString("GenerateHeading", resourceCulture)!;
        internal static string GenerateDescription => ResourceManager.GetString("GenerateDescription", resourceCulture)!;
        internal static string GenerateSectionHeader => ResourceManager.GetString("GenerateSectionHeader", resourceCulture)!;
        internal static string GenerateInstructions => ResourceManager.GetString("GenerateInstructions", resourceCulture)!;
        internal static string GenerateLabelRootFolder => ResourceManager.GetString("GenerateLabelRootFolder", resourceCulture)!;
        internal static string GeneratePlaceholderRootFolder => ResourceManager.GetString("GeneratePlaceholderRootFolder", resourceCulture)!;
        internal static string GenerateBrowseRootFolder => ResourceManager.GetString("GenerateBrowseRootFolder", resourceCulture)!;
        internal static string GenerateLabelOutputFolder => ResourceManager.GetString("GenerateLabelOutputFolder", resourceCulture)!;
        internal static string GeneratePlaceholderOutputFolder => ResourceManager.GetString("GeneratePlaceholderOutputFolder", resourceCulture)!;
        internal static string GenerateBrowseOutputFolder => ResourceManager.GetString("GenerateBrowseOutputFolder", resourceCulture)!;
        internal static string GenerateLabelPlanFileName => ResourceManager.GetString("GenerateLabelPlanFileName", resourceCulture)!;
        internal static string GeneratePlaceholderPlanFileName => ResourceManager.GetString("GeneratePlaceholderPlanFileName", resourceCulture)!;
        internal static string GenerateLabelGeneratedPlanPath => ResourceManager.GetString("GenerateLabelGeneratedPlanPath", resourceCulture)!;
        internal static string GenerateButtonGenerateAndLoad => ResourceManager.GetString("GenerateButtonGenerateAndLoad", resourceCulture)!;

        internal static string GenerateStatusDefault => ResourceManager.GetString("GenerateStatusDefault", resourceCulture)!;
        internal static string GenerateStatusRootCanceled => ResourceManager.GetString("GenerateStatusRootCanceled", resourceCulture)!;
        internal static string GenerateStatusRootSelected => ResourceManager.GetString("GenerateStatusRootSelected", resourceCulture)!;
        internal static string GenerateStatusOutputCanceled => ResourceManager.GetString("GenerateStatusOutputCanceled", resourceCulture)!;
        internal static string GenerateStatusOutputSelected => ResourceManager.GetString("GenerateStatusOutputSelected", resourceCulture)!;
        internal static string GenerateStatusInProgress => ResourceManager.GetString("GenerateStatusInProgress", resourceCulture)!;
        internal static string GenerateStatusSuccess => ResourceManager.GetString("GenerateStatusSuccess", resourceCulture)!;
        internal static string GenerateStatusUnavailable => ResourceManager.GetString("GenerateStatusUnavailable", resourceCulture)!;
        internal static string GenerateErrorNoRootTitle => ResourceManager.GetString("GenerateErrorNoRootTitle", resourceCulture)!;
        internal static string GenerateErrorNoRootMessage => ResourceManager.GetString("GenerateErrorNoRootMessage", resourceCulture)!;
        internal static string GenerateErrorInvalidRootTitle => ResourceManager.GetString("GenerateErrorInvalidRootTitle", resourceCulture)!;
        internal static string GenerateErrorInvalidRootMessage => ResourceManager.GetString("GenerateErrorInvalidRootMessage", resourceCulture)!;
        internal static string GenerateErrorNoOutputTitle => ResourceManager.GetString("GenerateErrorNoOutputTitle", resourceCulture)!;
        internal static string GenerateErrorNoOutputMessage => ResourceManager.GetString("GenerateErrorNoOutputMessage", resourceCulture)!;
        internal static string GenerateErrorNoFileNameTitle => ResourceManager.GetString("GenerateErrorNoFileNameTitle", resourceCulture)!;
        internal static string GenerateErrorNoFileNameMessage => ResourceManager.GetString("GenerateErrorNoFileNameMessage", resourceCulture)!;
        internal static string GenerateErrorInvalidFileNameTitle => ResourceManager.GetString("GenerateErrorInvalidFileNameTitle", resourceCulture)!;
        internal static string GenerateErrorInvalidFileNameMessage => ResourceManager.GetString("GenerateErrorInvalidFileNameMessage", resourceCulture)!;
        internal static string GenerateErrorFileSystemTitle => ResourceManager.GetString("GenerateErrorFileSystemTitle", resourceCulture)!;
        internal static string GenerateErrorFileSystemMessage => ResourceManager.GetString("GenerateErrorFileSystemMessage", resourceCulture)!;
        internal static string GenerateErrorUnexpectedTitle => ResourceManager.GetString("GenerateErrorUnexpectedTitle", resourceCulture)!;
        internal static string GenerateErrorUnexpectedMessage => ResourceManager.GetString("GenerateErrorUnexpectedMessage", resourceCulture)!;

        internal static string GenerateFolderPickerRootTitle => ResourceManager.GetString("GenerateFolderPickerRootTitle", resourceCulture)!;
        internal static string GenerateFolderPickerOutputTitle => ResourceManager.GetString("GenerateFolderPickerOutputTitle", resourceCulture)!;

        internal static string PreviewHeading => ResourceManager.GetString("PreviewHeading", resourceCulture)!;
        internal static string PreviewDescription => ResourceManager.GetString("PreviewDescription", resourceCulture)!;
        internal static string PreviewSectionHeader => ResourceManager.GetString("PreviewSectionHeader", resourceCulture)!;
        internal static string PreviewInstructions => ResourceManager.GetString("PreviewInstructions", resourceCulture)!;
        internal static string PreviewPlaceholder => ResourceManager.GetString("PreviewPlaceholder", resourceCulture)!;
        internal static string PreviewBrowse => ResourceManager.GetString("PreviewBrowse", resourceCulture)!;
        internal static string PreviewButtonLoad => ResourceManager.GetString("PreviewButtonLoad", resourceCulture)!;
        internal static string PreviewIdleLabel => ResourceManager.GetString("PreviewIdleLabel", resourceCulture)!;
        internal static string PreviewIdleDescription => ResourceManager.GetString("PreviewIdleDescription", resourceCulture)!;
        internal static string PreviewLoadingLabel => ResourceManager.GetString("PreviewLoadingLabel", resourceCulture)!;
        internal static string PreviewErrorHeading => ResourceManager.GetString("PreviewErrorHeading", resourceCulture)!;
        internal static string PreviewSummarySectionHeader => ResourceManager.GetString("PreviewSummarySectionHeader", resourceCulture)!;
        internal static string PreviewSummaryDescription => ResourceManager.GetString("PreviewSummaryDescription", resourceCulture)!;
        internal static string PreviewFieldRootPath => ResourceManager.GetString("PreviewFieldRootPath", resourceCulture)!;
        internal static string PreviewFieldCreatedAt => ResourceManager.GetString("PreviewFieldCreatedAt", resourceCulture)!;
        internal static string PreviewFieldOperations => ResourceManager.GetString("PreviewFieldOperations", resourceCulture)!;
        internal static string PreviewFieldWarnings => ResourceManager.GetString("PreviewFieldWarnings", resourceCulture)!;
        internal static string PreviewOperationsSectionHeader => ResourceManager.GetString("PreviewOperationsSectionHeader", resourceCulture)!;
        internal static string PreviewOperationsTotal => ResourceManager.GetString("PreviewOperationsTotal", resourceCulture)!;
        internal static string PreviewOperationsDescription => ResourceManager.GetString("PreviewOperationsDescription", resourceCulture)!;
        internal static string PreviewOperationFileCount => ResourceManager.GetString("PreviewOperationFileCount", resourceCulture)!;

        internal static string PreviewStatusDefault => ResourceManager.GetString("PreviewStatusDefault", resourceCulture)!;
        internal static string PreviewCreatedAtDefault => ResourceManager.GetString("PreviewCreatedAtDefault", resourceCulture)!;
        internal static string PreviewStatusPathUpdated => ResourceManager.GetString("PreviewStatusPathUpdated", resourceCulture)!;
        internal static string PreviewStatusBrowseOpening => ResourceManager.GetString("PreviewStatusBrowseOpening", resourceCulture)!;
        internal static string PreviewStatusBrowseCanceled => ResourceManager.GetString("PreviewStatusBrowseCanceled", resourceCulture)!;
        internal static string PreviewStatusBrowseSelected => ResourceManager.GetString("PreviewStatusBrowseSelected", resourceCulture)!;
        internal static string PreviewStatusBrowseError => ResourceManager.GetString("PreviewStatusBrowseError", resourceCulture)!;
        internal static string PreviewStatusRootOpened => ResourceManager.GetString("PreviewStatusRootOpened", resourceCulture)!;
        internal static string PreviewStatusRootError => ResourceManager.GetString("PreviewStatusRootError", resourceCulture)!;
        internal static string PreviewStatusNoPath => ResourceManager.GetString("PreviewStatusNoPath", resourceCulture)!;
        internal static string PreviewStatusLoading => ResourceManager.GetString("PreviewStatusLoading", resourceCulture)!;
        internal static string PreviewStatusLoadError => ResourceManager.GetString("PreviewStatusLoadError", resourceCulture)!;
        internal static string PreviewStatusLoaded => ResourceManager.GetString("PreviewStatusLoaded", resourceCulture)!;
        internal static string PreviewStatusUnavailable => ResourceManager.GetString("PreviewStatusUnavailable", resourceCulture)!;

        internal static string ApplyHeading => ResourceManager.GetString("ApplyHeading", resourceCulture)!;
        internal static string ApplyDescription => ResourceManager.GetString("ApplyDescription", resourceCulture)!;
        internal static string ApplyPlanArtifactSectionHeader => ResourceManager.GetString("ApplyPlanArtifactSectionHeader", resourceCulture)!;
        internal static string ApplyPlanArtifactInstructions => ResourceManager.GetString("ApplyPlanArtifactInstructions", resourceCulture)!;
        internal static string ApplyButtonBrowse => ResourceManager.GetString("ApplyButtonBrowse", resourceCulture)!;
        internal static string ApplyButtonLoadPlan => ResourceManager.GetString("ApplyButtonLoadPlan", resourceCulture)!;
        internal static string ApplyErrorHeading => ResourceManager.GetString("ApplyErrorHeading", resourceCulture)!;
        internal static string ApplySectionHeader => ResourceManager.GetString("ApplySectionHeader", resourceCulture)!;
        internal static string ApplyInstructions => ResourceManager.GetString("ApplyInstructions", resourceCulture)!;
        internal static string ApplyButtonRun => ResourceManager.GetString("ApplyButtonRun", resourceCulture)!;
        internal static string ApplySummarySectionHeader => ResourceManager.GetString("ApplySummarySectionHeader", resourceCulture)!;
        internal static string ApplyFieldOutcome => ResourceManager.GetString("ApplyFieldOutcome", resourceCulture)!;
        internal static string ApplyFieldDrifted => ResourceManager.GetString("ApplyFieldDrifted", resourceCulture)!;
        internal static string ApplyFieldStarted => ResourceManager.GetString("ApplyFieldStarted", resourceCulture)!;
        internal static string ApplyFieldFinished => ResourceManager.GetString("ApplyFieldFinished", resourceCulture)!;
        internal static string ApplyFieldSuccess => ResourceManager.GetString("ApplyFieldSuccess", resourceCulture)!;
        internal static string ApplyFieldSkipped => ResourceManager.GetString("ApplyFieldSkipped", resourceCulture)!;
        internal static string ApplyFieldFailed => ResourceManager.GetString("ApplyFieldFailed", resourceCulture)!;
        internal static string ApplyResultsSectionHeader => ResourceManager.GetString("ApplyResultsSectionHeader", resourceCulture)!;
        internal static string ApplyFieldPlannedDestination => ResourceManager.GetString("ApplyFieldPlannedDestination", resourceCulture)!;
        internal static string ApplyFieldActualDestination => ResourceManager.GetString("ApplyFieldActualDestination", resourceCulture)!;
        internal static string ApplyFieldResultWarnings => ResourceManager.GetString("ApplyFieldResultWarnings", resourceCulture)!;
        internal static string ApplyFieldError => ResourceManager.GetString("ApplyFieldError", resourceCulture)!;

        internal static string ApplyStatusDefault => ResourceManager.GetString("ApplyStatusDefault", resourceCulture)!;
        internal static string ApplyStatusOutcomeDefault => ResourceManager.GetString("ApplyStatusOutcomeDefault", resourceCulture)!;
        internal static string ApplyStatusStartedDefault => ResourceManager.GetString("ApplyStatusStartedDefault", resourceCulture)!;
        internal static string ApplyStatusFinishedDefault => ResourceManager.GetString("ApplyStatusFinishedDefault", resourceCulture)!;
        internal static string ApplyStatusInProgress => ResourceManager.GetString("ApplyStatusInProgress", resourceCulture)!;
        internal static string ApplyStatusPartial => ResourceManager.GetString("ApplyStatusPartial", resourceCulture)!;
        internal static string ApplyStatusSuccess => ResourceManager.GetString("ApplyStatusSuccess", resourceCulture)!;
        internal static string ApplyStatusUnavailable => ResourceManager.GetString("ApplyStatusUnavailable", resourceCulture)!;

        internal static string ApplyErrorTitleRetryAbort => ResourceManager.GetString("ApplyErrorTitleRetryAbort", resourceCulture)!;
        internal static string ApplyErrorTitleInvalidPlan => ResourceManager.GetString("ApplyErrorTitleInvalidPlan", resourceCulture)!;
        internal static string ApplyErrorTitleFileSystem => ResourceManager.GetString("ApplyErrorTitleFileSystem", resourceCulture)!;
        internal static string ApplyErrorTitleUnexpected => ResourceManager.GetString("ApplyErrorTitleUnexpected", resourceCulture)!;
        internal static string ApplyErrorTitleValidation => ResourceManager.GetString("ApplyErrorTitleValidation", resourceCulture)!;

        internal static string ApplyErrorMessageValidation => ResourceManager.GetString("ApplyErrorMessageValidation", resourceCulture)!;
        internal static string ApplyErrorMessageInvalidPlan => ResourceManager.GetString("ApplyErrorMessageInvalidPlan", resourceCulture)!;
        internal static string ApplyErrorMessageFileSystem => ResourceManager.GetString("ApplyErrorMessageFileSystem", resourceCulture)!;
        internal static string ApplyErrorMessageUnexpected => ResourceManager.GetString("ApplyErrorMessageUnexpected", resourceCulture)!;
    }
}
