//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renamer.Cli.Resources
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CliStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CliStrings() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan is null)
                {
                    resourceMan = new global::System.Resources.ResourceManager("Renamer.Cli.Resources.CliStrings", typeof(CliStrings).Assembly);
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string HelpHeader => ResourceManager.GetString("HelpHeader", resourceCulture)!;
        internal static string HelpCommandsLabel => ResourceManager.GetString("HelpCommandsLabel", resourceCulture)!;
        internal static string HelpCommandHelp => ResourceManager.GetString("HelpCommandHelp", resourceCulture)!;
        internal static string HelpCommandPlan => ResourceManager.GetString("HelpCommandPlan", resourceCulture)!;
        internal static string HelpCommandApply => ResourceManager.GetString("HelpCommandApply", resourceCulture)!;

        internal static string PlanErrorMissingArgs => ResourceManager.GetString("PlanErrorMissingArgs", resourceCulture)!;
        internal static string PlanErrorRootNotFound => ResourceManager.GetString("PlanErrorRootNotFound", resourceCulture)!;
        internal static string PlanErrorOutputIsDirectory => ResourceManager.GetString("PlanErrorOutputIsDirectory", resourceCulture)!;
        internal static string PlanErrorOutputNotWritable => ResourceManager.GetString("PlanErrorOutputNotWritable", resourceCulture)!;
        internal static string PlanErrorBuildFileSystem => ResourceManager.GetString("PlanErrorBuildFileSystem", resourceCulture)!;
        internal static string PlanErrorBuildUnexpected => ResourceManager.GetString("PlanErrorBuildUnexpected", resourceCulture)!;

        internal static string ApplyErrorMissingArgs => ResourceManager.GetString("ApplyErrorMissingArgs", resourceCulture)!;
        internal static string ApplyErrorPlanNotFound => ResourceManager.GetString("ApplyErrorPlanNotFound", resourceCulture)!;
        internal static string ApplyErrorPlanNotReadable => ResourceManager.GetString("ApplyErrorPlanNotReadable", resourceCulture)!;
        internal static string ApplyErrorInvalidSchema => ResourceManager.GetString("ApplyErrorInvalidSchema", resourceCulture)!;
        internal static string ApplyErrorReadFileSystem => ResourceManager.GetString("ApplyErrorReadFileSystem", resourceCulture)!;
        internal static string ApplyErrorOutputIsDirectory => ResourceManager.GetString("ApplyErrorOutputIsDirectory", resourceCulture)!;
        internal static string ApplyErrorOutputNotWritable => ResourceManager.GetString("ApplyErrorOutputNotWritable", resourceCulture)!;
        internal static string ApplyErrorEngineFileSystem => ResourceManager.GetString("ApplyErrorEngineFileSystem", resourceCulture)!;
        internal static string ApplyErrorEngineUnexpected => ResourceManager.GetString("ApplyErrorEngineUnexpected", resourceCulture)!;
    }
}
